version: '3.8'

services:
  acars-bot:
    image: ghcr.io/cartermh/acarsbot2:latest
    container_name: acarsbot2
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - acars-network

networks:
  acars-network:
    driver: bridge
